version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mlops"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vxr17cncuwft"
s3_prefix = "mlops"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
